kind: Deployment
apiVersion: apps/v1
metadata:
  name: mtls-proxy
  namespace: default
  labels:
    app: mtls-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-proxy
  template:
    metadata:
      labels:
        app: mtls-proxy
    spec:
      containers:
        - name: mtls-proxy
          image: docker.io/1rom2ny/mtls-proxy:v1
          imagePullPolicy: Always
      restartPolicy: Always      
      
---

apiVersion: v1
kind: Service
metadata:
  name: mtls-proxy
  namespace: default
  labels:
    app: mtls-proxy
spec:
  ports:
    - protocol: TCP
      port: 2700
      targetPort: 2700
      nodePort: 32722
  selector:
    app: mtls-proxy
  type: NodePort
