apiVersion: v1
kind: Service
metadata:
  name: mtls-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mtls-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2700

